### ISSUE TITLE
进入某个绘制了nifty-slider的Activity 在它finish时会导致崩溃

### ISSUE THREAD

**Issue by AhserAaAA** [litao0621/nifty-slider#1]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchDetachedFromWindow()' on a null object reference
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3934)
        at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:4652)
        at android.view.ViewRootImpl.doDie(ViewRootImpl.java:7697)
        at android.view.ViewRootImpl.die(ViewRootImpl.java:7674)
        at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:509)
        at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:450)
        at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:141)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5161)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        
        
        在这个Activity的XML中有一个Slider 然后当这个Activtyfinish时会导致崩溃 哪怕什么都不做 只是将其绘制出来

**Comment by AhserAaAA** [comment]
![image](https://github.com/litao0621/nifty-slider/assets/140790194/27e6e5ef-c2b1-4dc9-a8d5-b5dfe62974e4)
将 tipView.detachTipView(this)注释掉后 不再回导致此问题

**Comment by litao0621** [comment]
> detachTipView

直接运行demo会出现崩溃吗？我这无法复现，或者可以提供一个简单的存在问题的样例项目吗

**Comment by litao0621** [comment]
感谢反馈，已在1.4.1版本进行了修复，maven几小时后会同步，如使用中有其他问题或无法满足的效果可随时反馈。
