### ISSUE TITLE
在RecycleView中，设置了tipViewVisible为true，当数据更新时，如果比之前的数据少，就会崩溃

### ISSUE THREAD

**Issue by kalinte** [litao0621/nifty-slider#12]
复现的方式也很简单，在simple里面的ScrollContainerDemoFragment，将adapter对应的view，将NiftySlider控件的tipViewVisible设置为true，然后先将列表显示，之后再清空列表，就会出现。
崩溃日志是
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:296)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:282)
	at android.view.View.layout(View.java:24947)
	at android.view.ViewGroup.layout(ViewGroup.java:6490)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1896)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1734)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1643)
	at android.view.View.layout(View.java:24947)
	at android.view.ViewGroup.layout(ViewGroup.java:6490)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:348)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:282)
	at android.view.View.layout(View.java:24947)
	at android.view.ViewGroup.layout(ViewGroup.java:6490)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1896)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1734)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1643)
	at android.view.View.layout(View.java:24947)
	at android.view.ViewGroup.layout(ViewGroup.java:6490)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:348)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:282)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:1019)
	at android.view.View.layout(View.java:24947)
	at android.view.ViewGroup.layout(ViewGroup.java:6490)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4920)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4191)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2908)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10490)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1760)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1769)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1273)
	at android.view.Choreographer.doFrame(Choreographer.java:1140)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1743)
	at android.os.Handler.handleCallback(Handler.java:1013)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:328)
	at android.app.ActivityThread.main(ActivityThread.java:9239)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)

上面的崩溃信息，看不出是什么地方崩溃导致的，然后我自己调试了一下源码，是在BaseSlider#onDetachedFromWindow触发后，调用 tipView.detachTipView(this)，之后contentView?.removeView(this)这行代码调用后，不过也没有找到什么好的方法去解决，网上说的用post，试了一下，有效，但是清空后，再重新设置一下新的列表，又会崩溃

**Comment by litao0621** [comment]
v1.4.7 中修复了此问题 ，有其他问题随时提。
